// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewMovies.API.Data;

#nullable disable

namespace ReviewMovie.API.Migrations
{
	[DbContext(typeof(MovieReviewDbContext))]
    [Migration("20250220111149_alterations")]
    partial class alterations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReviewMovie.API.Data.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A story of hope and friendship.",
                            Genre = "Drama",
                            ReleaseDate = 1994,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 2,
                            Description = "An iconic mafia story.",
                            Genre = "Drama",
                            ReleaseDate = 1972,
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Batman faces the Joker.",
                            Genre = "Drama",
                            ReleaseDate = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Interwoven crime stories.",
                            Genre = "Drama",
                            ReleaseDate = 1994,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Life seen through Forrest's eyes.",
                            Genre = "Drama",
                            ReleaseDate = 1994,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A journey into dreams.",
                            Genre = "Drama",
                            ReleaseDate = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A psychological thriller.",
                            Genre = "Drama",
                            ReleaseDate = 1999,
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Reality is not what it seems.",
                            Genre = "Drama",
                            ReleaseDate = 1999,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A journey beyond the stars.",
                            Genre = "Drama",
                            ReleaseDate = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The final battle for Middle-earth.",
                            Genre = "Drama",
                            ReleaseDate = 2003,
                            Title = "The Lord of the Rings: The Return of the King"
                        });
                });

            modelBuilder.Entity("ReviewMovie.API.Data.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "An unforgettable masterpiece.",
                            MovieId = 1,
                            Rating = 7,
                            ReviewerName = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "A deeply moving story of hope.",
                            MovieId = 1,
                            Rating = 9,
                            ReviewerName = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "The greatest crime film ever made.",
                            MovieId = 2,
                            Rating = 5,
                            ReviewerName = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "A timeless classic with incredible performances.",
                            MovieId = 2,
                            Rating = 6,
                            ReviewerName = "David"
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Heath Ledger's Joker is legendary.",
                            MovieId = 3,
                            Rating = 10,
                            ReviewerName = "Eve"
                        },
                        new
                        {
                            Id = 6,
                            Comment = "A dark and thrilling superhero film.",
                            MovieId = 3,
                            Rating = 4,
                            ReviewerName = "Frank"
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Quentin Tarantino at his finest.",
                            MovieId = 4,
                            Rating = 8,
                            ReviewerName = "Grace"
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Brilliant dialogues and unforgettable characters.",
                            MovieId = 4,
                            Rating = 5,
                            ReviewerName = "Hank"
                        },
                        new
                        {
                            Id = 9,
                            Comment = "A heartwarming tale of an extraordinary life.",
                            MovieId = 5,
                            Rating = 10,
                            ReviewerName = "Ivy"
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Tom Hanks delivers a phenomenal performance.",
                            MovieId = 5,
                            Rating = 6,
                            ReviewerName = "Jack"
                        },
                        new
                        {
                            Id = 11,
                            Comment = "A mind-bending sci-fi thriller.",
                            MovieId = 6,
                            Rating = 9,
                            ReviewerName = "Karen"
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Nolan's masterpiece with stunning visuals.",
                            MovieId = 6,
                            Rating = 7,
                            ReviewerName = "Leo"
                        },
                        new
                        {
                            Id = 13,
                            Comment = "A gripping and thought-provoking film.",
                            MovieId = 7,
                            Rating = 10,
                            ReviewerName = "Mia"
                        },
                        new
                        {
                            Id = 14,
                            Comment = "A mind-blowing twist and brilliant acting.",
                            MovieId = 7,
                            Rating = 9,
                            ReviewerName = "Nate"
                        },
                        new
                        {
                            Id = 15,
                            Comment = "A sci-fi revolution in filmmaking.",
                            MovieId = 8,
                            Rating = 5,
                            ReviewerName = "Olivia"
                        },
                        new
                        {
                            Id = 16,
                            Comment = "An iconic action-packed adventure.",
                            MovieId = 8,
                            Rating = 9,
                            ReviewerName = "Paul"
                        },
                        new
                        {
                            Id = 17,
                            Comment = "A visually stunning and emotional journey.",
                            MovieId = 9,
                            Rating = 9,
                            ReviewerName = "Quinn"
                        },
                        new
                        {
                            Id = 18,
                            Comment = "One of the best space movies ever made.",
                            MovieId = 9,
                            Rating = 9,
                            ReviewerName = "Rachel"
                        },
                        new
                        {
                            Id = 19,
                            Comment = "An epic conclusion to an incredible trilogy.",
                            MovieId = 10,
                            Rating = 6,
                            ReviewerName = "Steve"
                        },
                        new
                        {
                            Id = 20,
                            Comment = "Visually breathtaking and emotionally powerful.",
                            MovieId = 10,
                            Rating = 9,
                            ReviewerName = "Tina"
                        });
                });

            modelBuilder.Entity("ReviewMovie.API.Data.Review", b =>
                {
                    b.HasOne("ReviewMovie.API.Data.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("ReviewMovie.API.Data.Movie", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
