// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewMovie.API.Data;

#nullable disable

namespace ReviewMovie.API.Migrations
{
    [DbContext(typeof(MovieReviewDbContext))]
    [Migration("20250221143146_identityAdded")]
    partial class identityAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ReviewMovie.API.Data.ApiUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ReviewMovie.API.Data.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A story of hope and friendship.",
                            Genre = "Drama",
                            ReleaseDate = 1994,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 2,
                            Description = "An iconic mafia story.",
                            Genre = "Drama",
                            ReleaseDate = 1972,
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Batman faces the Joker.",
                            Genre = "Drama",
                            ReleaseDate = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Interwoven crime stories.",
                            Genre = "Drama",
                            ReleaseDate = 1994,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Life seen through Forrest's eyes.",
                            Genre = "Drama",
                            ReleaseDate = 1994,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A journey into dreams.",
                            Genre = "Drama",
                            ReleaseDate = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A psychological thriller.",
                            Genre = "Drama",
                            ReleaseDate = 1999,
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Reality is not what it seems.",
                            Genre = "Drama",
                            ReleaseDate = 1999,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A journey beyond the stars.",
                            Genre = "Drama",
                            ReleaseDate = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The final battle for Middle-earth.",
                            Genre = "Drama",
                            ReleaseDate = 2003,
                            Title = "The Lord of the Rings: The Return of the King"
                        });
                });

            modelBuilder.Entity("ReviewMovie.API.Data.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "An unforgettable masterpiece.",
                            MovieId = 1,
                            Rating = 7,
                            ReviewerName = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "A deeply moving story of hope.",
                            MovieId = 1,
                            Rating = 9,
                            ReviewerName = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "The greatest crime film ever made.",
                            MovieId = 2,
                            Rating = 5,
                            ReviewerName = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "A timeless classic with incredible performances.",
                            MovieId = 2,
                            Rating = 6,
                            ReviewerName = "David"
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Heath Ledger's Joker is legendary.",
                            MovieId = 3,
                            Rating = 10,
                            ReviewerName = "Eve"
                        },
                        new
                        {
                            Id = 6,
                            Comment = "A dark and thrilling superhero film.",
                            MovieId = 3,
                            Rating = 4,
                            ReviewerName = "Frank"
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Quentin Tarantino at his finest.",
                            MovieId = 4,
                            Rating = 8,
                            ReviewerName = "Grace"
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Brilliant dialogues and unforgettable characters.",
                            MovieId = 4,
                            Rating = 5,
                            ReviewerName = "Hank"
                        },
                        new
                        {
                            Id = 9,
                            Comment = "A heartwarming tale of an extraordinary life.",
                            MovieId = 5,
                            Rating = 10,
                            ReviewerName = "Ivy"
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Tom Hanks delivers a phenomenal performance.",
                            MovieId = 5,
                            Rating = 6,
                            ReviewerName = "Jack"
                        },
                        new
                        {
                            Id = 11,
                            Comment = "A mind-bending sci-fi thriller.",
                            MovieId = 6,
                            Rating = 9,
                            ReviewerName = "Karen"
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Nolan's masterpiece with stunning visuals.",
                            MovieId = 6,
                            Rating = 7,
                            ReviewerName = "Leo"
                        },
                        new
                        {
                            Id = 13,
                            Comment = "A gripping and thought-provoking film.",
                            MovieId = 7,
                            Rating = 10,
                            ReviewerName = "Mia"
                        },
                        new
                        {
                            Id = 14,
                            Comment = "A mind-blowing twist and brilliant acting.",
                            MovieId = 7,
                            Rating = 9,
                            ReviewerName = "Nate"
                        },
                        new
                        {
                            Id = 15,
                            Comment = "A sci-fi revolution in filmmaking.",
                            MovieId = 8,
                            Rating = 5,
                            ReviewerName = "Olivia"
                        },
                        new
                        {
                            Id = 16,
                            Comment = "An iconic action-packed adventure.",
                            MovieId = 8,
                            Rating = 9,
                            ReviewerName = "Paul"
                        },
                        new
                        {
                            Id = 17,
                            Comment = "A visually stunning and emotional journey.",
                            MovieId = 9,
                            Rating = 9,
                            ReviewerName = "Quinn"
                        },
                        new
                        {
                            Id = 18,
                            Comment = "One of the best space movies ever made.",
                            MovieId = 9,
                            Rating = 9,
                            ReviewerName = "Rachel"
                        },
                        new
                        {
                            Id = 19,
                            Comment = "An epic conclusion to an incredible trilogy.",
                            MovieId = 10,
                            Rating = 6,
                            ReviewerName = "Steve"
                        },
                        new
                        {
                            Id = 20,
                            Comment = "Visually breathtaking and emotionally powerful.",
                            MovieId = 10,
                            Rating = 9,
                            ReviewerName = "Tina"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ReviewMovie.API.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ReviewMovie.API.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReviewMovie.API.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ReviewMovie.API.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReviewMovie.API.Data.Review", b =>
                {
                    b.HasOne("ReviewMovie.API.Data.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("ReviewMovie.API.Data.Movie", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
